language: bash
python:
  - "2.7"
# command to install dependencies
# command to run tests

env:
  - POPPER_HOST_CONFIG_LIST=$TRAVIS_BUILD_DIR/host_config.json POPPER_CONFIG=$TRAVIS_BUILD_DIR/popper_config.json PYTHONPATH=$TRAVIS_BUILD_DIR/src
script:
  - echo $TRAVIS_BUILD_DIR # or py.test for Python versions 3.5 and below