language: python
python:
  - "2.7"
# command to install dependencies
# command to run tests

script:
  - export POPPER_HOST_CONFIG_LIST=$TRAVIS_BUILD_DIR/host_config.json
  - export POPPER_CONFIG=$TRAVIS_BUILD_DIR/popper_config.json
  - export PYTHONPATH=$TRAVIS_BUILD_DIR/src
  - python client_test.py
  - python popper_test.py